### ISSUE TITLE
Local root dependency prevents use of the library

### ISSUE THREAD

**Issue by respatialized** [adam-james-v/svg-clj#15]
Hi @adam-james-v ! I just tried to update to the latest git version of `svg-clj`, but got a dependency resolution error because `eyebrowse` has a local root dep coordinate. Is this because the new git version depends on unpushed changes to [eyebrowse](https://github.com/adam-james-v/eyebrowse)? Should I fall back to the previous version for the time being?

**Comment by respatialized** [comment]
I was able to get around this error by manually specifying the Git coordinate for `eyebrowse`.

**Comment by adam-james-v** [comment]
Really sorry about that, I let the state of this project get a bit messy, and this is an unfortunate result. I'll be improving my approach to things, so stuff like this should (hopefully) not happen again. 

I believe the latest push to the main branch should fix this -> that eyebrowse thing was purely an experiment anyway, and should not be needed for this library at all.
